version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db: