# Generated by Django 5.0 on 2023-12-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "sound_equipment",
                    models.BooleanField(default=False, verbose_name="Оборудование"),
                ),
                ("stage", models.BooleanField(default=False, verbose_name="Сцена")),
                (
                    "lighting",
                    models.BooleanField(default=False, verbose_name="Освещение"),
                ),
            ],
            options={
                "verbose_name": "Музыкальная площадка",
                "verbose_name_plural": "Музыкальные площадки",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AvailabilitySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("opening_time", models.TimeField(verbose_name="Время открытия")),
                ("closing_time", models.TimeField(verbose_name="Время закрытия")),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="venues.musicvenue",
                        verbose_name="Площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "График доступности",
                "verbose_name_plural": "Графики доступности",
                "ordering": ("venue",),
            },
        ),
        migrations.AddConstraint(
            model_name="availabilityschedule",
            constraint=models.UniqueConstraint(
                fields=("venue", "date"), name="venue_date_constraint"
            ),
        ),
    ]
